version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "/var/docker/lnmp/conf:/etc/mysql"
      - "/var/docker/lnmp/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      TZ: "Asia/Shanghai"
    restart: always
  php:
    image: php:7.2-fpm
    links:
      - "mysql:lnmp_mysql"
    volumes:
      - "/var/www:/var/www"
    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      TZ: "Asia/Shanghai"
  nginx:
    image: nginx:1.17
    links:
      - "php:lnmp_php"
    ports:
      - "80:80"
    volumes:
      - "/var/docker/lnmp/nginx/logs:/var/log/nginx"
      - "/var/www:/var/www"
      - "/var/docker/lnmp/nginx/etc:/etc/nginx"
    restart: always
    environment:
      TZ: "Asia/Shanghai"
